//te dice si el alumno reprueba o no
real n1, n2, n3, p
inicio 
	escriba "Digite nota #1 de 1 a 100: "
		lea n1
	escriba "Digite nota #2 de 1 a 100: "
		lea n2
	escriba "Digite nota #3 de 1 a 100: "
		lea n3
	
	p<-(n1+n2+n3)/3
	
	si (p>=60) y (p<=100)entonces
		escriba "El alumno gano el curso con ",p," puntos"
		sino
			si (p<60)entonces
				escriba "El alumno reprobo con ",p," puntos"	
			fin si
	fin si
fin